# Site settings
title: "Vitor de Lima Cirqueira"
description: "Currículo Vitae"

# Language settings
lang: "pt-br"

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Vitor de Lima Cirqueira"
resume_contact_email:           "vitorcirqueira@gmail.com"
resume_header_contact_info:     "vitorcirqueira@gmail.com"
resume_header_intro:           "<p>28 anos / E-mail: vitorcirqueira@gmail.com</p>"
resume_looking_for_work:        "yes"

# Sections to display
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       false

# Social links
resume_social_links:
  resume_github_url:            "https://github.com/vitorlc"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "https://www.facebook.com/vitor.lima.967"
  resume_linkedin_url:          "https://www.linkedin.com/in/vitorlc"
  # resume_instagram_url:         "https://www.instagram.com/vitor.lc/"
  #resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default 